name: github pages

on:
  pull_request:
    types: [closed]
    branches:
      - master

  push:
    branches:
      - master
  
  watch:
    types: [started]

jobs:
  build-deploy:
    if: github.event.repository.owner.id == github.event.sender.id
    
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: .
